// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oidctoken")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidctokenextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
